name: tests-locale
on:
  push:
    branches: ['main']
    paths-ignore:
      - "docs/*"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/*"
      - "**.md"
permissions: read-all
jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.24']
    runs-on: ubuntu-latest
    steps:
    - name: Set locale
      run: |
        sudo apt-get update && sudo apt-get install tzdata locales -y
        sudo sed -i '/fr_FR.UTF-8/s/^# //g' /etc/locale.gen && sudo locale-gen
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    - name: Install Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    - name: Test
      run: go test -timeout 20m ./...
      env:
        LANG: "fr_FR.UTF-8"
        LANGUAGE: "fr_FR:fr"
        LC_ALL: "fr_FR.UTF-8"
