name: tests
on:
  push:
    branches: ['main']
    paths-ignore:
      - "docs/*"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/*"
      - "**.md"
permissions: read-all
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.24']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
    - name: Install Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    - name: Test
      run: go test -race -timeout 20m ./...
