name: get-started-tests
on:
  push:
    branches: ['main']
    paths-ignore:
      - "docs/**"
      - "!docs/testing/**"
      - "!docs/get-started.md"
      - "*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "!docs/testing/**"
      - "!docs/get-started.md"
      - "*.md"
permissions: read-all
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.24']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
    - name: Install Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    - name: Install Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: '3.10'
    - name: Build gittuf
      run: make just-install
    - name: Test Getting Started
      run: python3 docs/testing/test-get-started-md.py
