name: git 2.34.1 on ubuntu-22.04
on:
  push:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
permissions: read-all
jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.24', '1.25']
    runs-on: ubuntu-22.04
    steps:
      - name: Downgrade Git
        run: sudo apt-get update && sudo apt-get install -y --allow-downgrades git=1:2.34.1-1ubuntu1.15 git-man=1:2.34.1-1ubuntu1.15
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Test
        run: go test ./...
